CHECKPOINT_PATH: "/home/qiutianyuan/workspace/Foreground-Reconstruction/checkpoint"
LOOP_TIME_PER_EPOCH: 1000

DATASET_PATH: "/data/tanlinfeng/IHD/HFlickr"
OUTPUT_PATH: "/home/qiutianyuan/workspace/Foreground-Reconstruction/testspace/RESULT"

LUT_PATH: "/home/qiutianyuan/workspace/Foreground-Reconstruction/testspace/lut"